
services:
  api:
    image: python:3.11-slim
    working_dir: /app
    command: bash -lc "pip install -r requirements.txt && uvicorn web-dashboard.main:app --host 0.0.0.0 --port 8000"
    volumes: [ ".:/app" ]
    ports: [ "8000:8000" ]

volumes:
      - ./provisioning/grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./provisioning/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana:/var/lib/grafana/dashboards:ro

  exporter:
    image: python:3.11-slim
    working_dir: /app
    command: bash -lc "pip install -r requirements.txt && python monitoring/prometheus_exporter.py"
    volumes: [ ".:/app" ]
    ports: [ "9108:9108" ]

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports: [ "9090:9090" ]

  grafana:
    image: grafana/grafana:latest
    ports: [ "3000:3000" ]
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
